# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftLocation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for SwiftLocation
	pod 'SwiftLocation/Core'
	pod 'SwiftLocation/BeaconBroadcaster'
end
